#!/usr/bin/env python3

# Copyright 2011, Marc Garcia <garcia.marc@gmail.com>
#
# This file is part of Viri.
#
# Viri is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3 of the License.
#
# Viri is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Viri.  If not, see <http://www.gnu.org/licenses/>.

"""Script for executing viri tests.

Usage:
    tests.py [modules_to_test]

    modules_to_test: Optional list of test modules to execute, if not provided,
        all test modules are tested

Example usage:
    tests.py -- Executes all tests
    tests.py schedserver -- Executes schedserver.py tests
    tests.py schedserver rpcserver -- Executes schedserver.py and rpcserver.py
        tests
"""

import sys
import doctest

ALL_TESTS = ('rpcserver', 'schedserver', 'viric')

def set_path():
    from os.path import join, dirname, abspath
    sys.path.insert(0, join(dirname(dirname(abspath(__file__))), 'virid'))

def exec_tests(tests):
    for test in tests:
        test_mod = __import__('%s_tests' % test, globals(), locals())
        doctest.testmod(test_mod)

if __name__ == '__main__':
    set_path()
    if len(sys.argv) == 1:
        exec_tests(ALL_TESTS)
    else:
        exec_tests(sys.argv[1:])

