#!/bin/sh

# Copyright 2011, Marc Garcia <garcia.marc@gmail.com>
#
# This file is part of Viri.
#
# Viri is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3 of the License.
#
# Viri is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Viri.  If not, see <http://www.gnu.org/licenses/>.

echo "###################################################"
echo "###          CERTIFICATION AUTHORITY            ###"
echo "###################################################"
openssl req -x509 -nodes -newkey rsa:4096 -keyout ca.key -out ca.cert -days 3650
mkdir demoCA
touch demoCA/index.txt
echo "00" > demoCA/serial

echo "###################################################"
echo "###          VIRI CLIENT                        ###"
echo "###################################################"
openssl genrsa 4096 > viric.key
openssl req -new -key viric.key -out viric.csr
openssl ca -in viric.csr -cert ca.cert -keyfile ca.key -policy policy_anything -outdir . -out viric.pem -days 3650
cat viric.key >> viric.pem

echo "###################################################"
echo "###          VIRI DAEMON                        ###"
echo "###################################################"
openssl req -new -newkey rsa:4096 -nodes -x509 -keyout virid.pem -out virid.pem -days 3650

rm -rf 00.pem ca.key demoCA viric.csr viric.key

